on: [pull_request]
jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      TF_ROOT: Infra-EKS
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: 'base'

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost cost estimate baseline for base branch
        run: |
          #cd base/${{ env.TF_ROOT }}
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          path: 'pr'

      - name: Generate Infracost diff for PR branch
        run: |
          #cd pr/${{ env.TF_ROOT }}
          infracost diff --path=. \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost-diff.json

      - name: Post detailed Infracost comment
        run: |
          jq '.projects[] | {projectName: .name, pastCost: .pastTotalMonthlyCost, newCost: .totalMonthlyCost, diff: .diffTotalMonthlyCost}' /tmp/infracost-diff.json > /tmp/parsed_costs.json
          
          echo "### Cost Analysis" > comment.md
          echo "| Project | Previous Cost | New Cost | Cost Difference |" >> comment.md
          echo "|---------|--------------|----------|-----------------|" >> comment.md
          jq -r '[.[]] | "\(.projectName) | \(.pastCost) | \(.newCost) | \(.diffTotalMonthlyCost // "N/A") |"' /tmp/parsed_costs.json >> comment.md
          
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

